# Inherit style from another configuration
inherit_from: .rubocop_todo.yml

# Apply rule to all cops
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.4

#################### Style #################################

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

#################### Rails #################################

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true
